"""initial

Revision ID: 8ed09ae44fda
Revises: 
Create Date: 2026-04-15 11:42:34.529612
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8ed09ae44fda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('norm_query', sa.String(length=500), nullable=True),
    sa.Column('old_bid', sa.Integer(), nullable=True),
    sa.Column('new_bid', sa.Integer(), nullable=True),
    sa.Column('position_before', sa.Integer(), nullable=True),
    sa.Column('position_after', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_logs_campaign_id'), 'bid_logs', ['campaign_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wb_campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('bid_type', sa.String(length=20), nullable=True),
    sa.Column('is_bidder_active', sa.Boolean(), nullable=True),
    sa.Column('max_bid', sa.Integer(), nullable=True),
    sa.Column('budget_total', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_wb_campaign_id'), 'campaigns', ['wb_campaign_id'], unique=True)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('norm_query', sa.String(length=500), nullable=False),
    sa.Column('target_position', sa.Integer(), nullable=True),
    sa.Column('max_bid', sa.Integer(), nullable=True),
    sa.Column('current_bid', sa.Integer(), nullable=True),
    sa.Column('is_bidding_active', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('avg_position', sa.Float(), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('add_to_cart', sa.Integer(), nullable=True),
    sa.Column('cart_price', sa.Float(), nullable=True),
    sa.Column('is_auto_minus', sa.Boolean(), nullable=True),
    sa.Column('auto_minus_threshold', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'nm_id', 'norm_query', name='uq_cluster')
    )
    op.create_index(op.f('ix_clusters_campaign_id'), 'clusters', ['campaign_id'], unique=False)
    op.create_table('minus_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('norm_query', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('views_at_creation', sa.Integer(), nullable=True),
    sa.Column('views_current', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'nm_id', 'norm_query', name='uq_minus')
    )
    op.create_index(op.f('ix_minus_queue_campaign_id'), 'minus_queue', ['campaign_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_campaign_id'), 'schedules', ['campaign_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_campaign_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_minus_queue_campaign_id'), table_name='minus_queue')
    op.drop_table('minus_queue')
    op.drop_index(op.f('ix_clusters_campaign_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_campaigns_wb_campaign_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_bid_logs_campaign_id'), table_name='bid_logs')
    op.drop_table('bid_logs')
    # ### end Alembic commands ###
