"""add buyout_percent and avg_price_api to products

Revision ID: add_buyout_percent_to_products
Revises: 437bceeccdd8
Create Date: 2026-05-12 07:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_buyout_percent_to_products'
down_revision = '437bceeccdd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('buyout_percent', sa.Integer(), nullable=True, default=0))
    op.add_column('products', sa.Column('avg_price_api', sa.Float(), nullable=True, default=0.0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'buyout_percent')
    op.drop_column('products', 'avg_price_api')
    # ### end Alembic commands ###